<?php

namespace Todo\ComBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends EntityRepository
{
public function findByPT($date)
{
  $qb = $this->createQueryBuilder('a');

  $qb->where('a.date > :date')
         ->setParameter('date', $date)
	 ->orderBy('a.date', 'DESC')
  ;

  return $qb
    ->getQuery()
    ->getResult()
  ;
}
}
